"""`docs/TELEMANOM_EXCERPTS.md`'s index matches the tree, and nothing else moved.

Section 5 is generated by `scripts/telemanom_citations.py`. Section 4 is nine
hand-written findings and is not. They sit in the same document and both begin
with a `| Location` cell, which is how a regeneration anchored on that prefix
came to overwrite section 4 and take the nine findings with it. That mistake is
what this module is for: the generated table is pinned to the generator, and the
hand-written one is pinned to being present.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import telemanom_citations as T  # noqa: E402

INDEX = ROOT / "docs" / "TELEMANOM_EXCERPTS.md"


def document() -> str:
    return INDEX.read_text(encoding="utf-8")


def test_the_generated_index_is_what_the_generator_produces() -> None:
    """Regeneration is a no-op, so drift is a diff and not an audit."""
    lines = document().splitlines()
    start = lines.index(T.TABLE_HEADER)
    end = start
    while end < len(lines) and lines[end].startswith("|"):
        end += 1
    assert "\n".join(lines[start:end]) == T.table(T.citations())


def test_the_hand_written_mechanism_table_is_still_there() -> None:
    """Section 4 is analysis, not an index, and no generator may touch it."""
    text = document()
    assert "| Location | Mechanism | What it settled |" in text
    for row in ("`errors.py:355-359`", "`detector.py:117-136`",
                "`modeling.py:113`, called at `:172`"):
        assert row in text, f"section 4 lost its row for {row}"


def test_the_two_tables_are_distinct_and_the_anchor_is_unique() -> None:
    lines = document().splitlines()
    assert lines.count(T.TABLE_HEADER) == 1, "the generated table's anchor must be unique"
    assert lines.count("| Location | Mechanism | What it settled |") == 1


def test_no_citation_overruns_the_file_it_names() -> None:
    assert T.overruns(T.citations()) == []


def test_the_stated_count_matches_the_table() -> None:
    found = T.citations()
    citers = {c for v in found.values() for c in v}
    text = document()
    assert f"**{len(found)} distinct locations are cited across {len(citers)} files**" in text


def test_the_generator_runs_clean_from_the_command_line() -> None:
    proc = subprocess.run([sys.executable, "scripts/telemanom_citations.py", "--check"],
                          cwd=ROOT, capture_output=True, text=True)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert "distinct locations" in proc.stdout
