// ======================================================================
// \title  Retrainer.hpp
// \brief  The retrainer: an F' shell around RetrainLoop, in its own process
//
// Exported OPT-IN (`docs/DECISIONS.md` D84): `fprime/library.cmake` registers it only
// when SENTINEL_WITH_RETRAINER is ON, so a mission that does nothing inherits no OCaml
// runtime. The chosen retraining implementation, host-verified, not flight-qualified
// (D83). It runs in its own process, never beside the detector (D70 consequence 2).
//
// D85: IT LEARNS FROM THE SPACECRAFT'S OWN TELEMETRY. Samples arrive from the
// SampleTap in the detector's process, over the hub; RetrainLoop (RetrainLoop.hpp)
// admits only recent healthy windows -- 56's rule plus a guard band around every
// detector crossing -- and trains the generated cycle on them at a fixed step budget,
// writing a candidate every E admitted steps. The synthetic drive and E1's
// accumulator are gone from this path; E1 survives as a unit-test fixture only.
//
// (!) NOTHING HERE MAY THROW, AND NOTHING BELOW IT CAN (CPP-25): every OCaml entry
// point is wrapped in a guard that turns an exception into a status.
// (!) NOTHING HERE ALLOCATES AFTER INIT (CPP-1): the loop, the queue and the file
// buffers are members of fixed size.
// ======================================================================

#ifndef Sentinel_Retrainer_HPP
#define Sentinel_Retrainer_HPP

#include <Os/Mutex.hpp>

#include "Sentinel/Retrainer/RetrainerComponentAc.hpp"
#include "RetrainLoop.hpp"

// D84: the cycle's shape, GENERATED by scripts/oxcaml_shape.py in the same step as the
// OCaml it is linked against. The F' build puts the selected shape's directory on the
// include path and refuses if it is absent or disagrees.
#include "sentinel_cycle_shape.h"

namespace Sentinel {

class Retrainer final : public RetrainerComponentBase {
  public:
    //! Samples queued between two ticks, at most. The tap and this component run on
    //! two clocks, so a tick may see zero, one or two samples; the bound makes the
    //! per-tick work fixed (Objective.md 11 rule 5) and an overrun is counted as
    //! missed samples rather than grown into.
    static const U32 QUEUE = 8U;

    explicit Retrainer(const char* const compName);
    ~Retrainer();

    //! Name the flying model file (read once, at boot) and the path each candidate is
    //! written to. Topology setup, never a command.
    void configureShadow(const char* flyingPath, const char* candidatePath);

    //! The loop's constants -- the dictionary's yellow bands, the guard band, the
    //! EXPERIMENTAL step budget and schedule, the model's nominal rate. Before boot.
    //! Returns false on a configuration the loop refuses.
    bool configureLoop(const LoopConfig& config);

    //! Boot the OCaml runtime, load the flying model into the replica and warm-start
    //! the cycle. Called on the first tick, on the rate-group thread.
    bool boot();

    //! docs/MODELS.md 78.11, LC2: apparatus, off unless the deployment asks. On, every
    //! sample the replica emitted on is logged by its tap sequence number, with the first
    //! sequence fed, every gap filled, and a heartbeat, so the replica's emits can be
    //! compared tick for tick with the detector's. Off, nothing here changes.
    void setEmitLog(bool enabled) { m_emitLog = enabled; }

    //! LC2's heartbeat period, in tap sequence numbers.
    static const U32 HEARTBEAT = 1000U;

    bool armed() const { return m_armed; }
    const RetrainLoop& loop() const { return m_loop; }
    U32 samplesReceived() const { return m_received; }
    U32 samplesMissed() const { return m_missed; }

  private:
    void schedIn_handler(FwIndexType portNum, U32 context) override;
    void sampleIn_handler(FwIndexType portNum, Sentinel::ChannelVector& values, bool valid,
                          U32 seq) override;

    //! Read the flying model file. Returns its length, or 0. No OCaml call.
    U32 readFlying();
    //! Write the loop's last candidate out and report it, in the tap's sequence
    //! numbers (`lastOffset` is sequence minus loop tick now). No OCaml call.
    void emitCandidate(U32 lastOffset);
    //! One sample through the loop. Called only from schedIn_handler. `offset` is the
    //! sample's sequence number minus the loop tick it is fed at.
    void feed(const F32* values, bool valid, U32 offset);

    RetrainLoop m_loop;
    bool m_configured;
    bool m_armed;
    bool m_bootAttempted;

    //! The queue the hub thread fills and the rate-group thread drains.
    Os::Mutex m_lock;
    F32 m_queue[QUEUE][Config::MAX_CHANNELS];
    bool m_queueValid[QUEUE];
    U32 m_queueSeq[QUEUE];
    U32 m_queued;
    U32 m_overrun;

    //! Drained copies, so no OCaml call is made while the lock is held.
    F32 m_batch[QUEUE][Config::MAX_CHANNELS];
    bool m_batchValid[QUEUE];
    U32 m_batchSeq[QUEUE];

    bool m_haveSeq;
    U32 m_nextSeq;
    //! Sequence minus loop tick at the current candidate's first admitted step. A
    //! span never crosses a gap (a missed tick flags the ring), so one offset holds.
    U32 m_spanOffset;
    U32 m_received;
    U32 m_missed;
    bool m_emitLog;          //!< LC2's log (78.11); off by default
    bool m_lastEmitted;      //!< the replica emitted on the last sample fed

    U8 m_file[RetrainLoop::FILE_MAX_BYTES];
    Fw::String m_flyingPath;
    Fw::String m_candidatePath;
};

}  // namespace Sentinel

#endif
