"""Generate the tables of contents for `docs/MODELS.md` and `docs/DECISIONS.md`.

Both are long enough that a reader cannot find anything by scrolling --
`docs/MODELS.md` carries over four hundred headings and `docs/DECISIONS.md` sixty-
eight entries -- and `docs/REORG_PLAN.md` tranche 3 asks for a table of contents in
each. **Generated, never hand-maintained**: a hand-written index of that size
drifts, and the drift is invisible until somebody follows a line that is wrong.

(!) IN DOCUMENT ORDER, NOT NUMERIC ORDER, AND WHERE THEY DISAGREE IT SAYS SO.
Two sections of `docs/MODELS.md` sit after sections that number above them --
33.6 follows 33.7 and 33.8, and 34.7 follows 34.8 -- because each is a "what
follows" block appended once the observations it looks past had landed. **Neither
is moved**: they are committed prose in a document whose numbering is cited from
629 places, and reordering them to flatter a table of contents would be the table
of contents wagging the document. The generator reports the departure instead.

(!) AND 26.6 APPEARS TWICE ON PURPOSE. The first is the reserved placeholder as it
stood before the run, kept because it records the pre-registration's shape; the
second is the result. Distinguished by heading text on 2026-09-09 so anchors
resolve, and listed here as the two entries it is.

Run: `.venv/bin/python scripts/make_tocs.py [--check]`
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

BEGIN = "<!-- toc: generated by scripts/make_tocs.py -->"
END = "<!-- /toc -->"

#: `## 12. Title` or `### 12.3 Title`. The number is what everything cites.
HEADING = re.compile(r"^(#{2,3})\s+(\d+(?:\.\d+)*[a-z]?)\.?\s+(.*)$")
#: `## D42. Title`
DECISION = re.compile(r"^##\s+(D\d+)\.\s+(.*)$")


def anchor(text: str) -> str:
    """GitHub's slug: lowercase, punctuation dropped, spaces to hyphens."""
    slug = text.lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    return re.sub(r"[\s_]+", "-", slug).strip("-")


def numeric_key(number: str) -> tuple:
    out = []
    for part in number.split("."):
        m = re.match(r"(\d+)([a-z]?)", part)
        out.append((int(m.group(1)), m.group(2)))
    return tuple(out)


def models_toc(text: str) -> tuple[str, list[str]]:
    rows, seen, out_of_order = [], {}, []
    previous = None
    for line in text.splitlines():
        m = HEADING.match(line)
        if not m:
            continue
        depth, number, title = len(m.group(1)), m.group(2), m.group(3).strip()
        full = f"{number}. {title}" if depth == 2 else f"{number} {title}"
        rows.append((depth, number, title, anchor(full)))
        if previous is not None and numeric_key(number) < numeric_key(previous):
            out_of_order.append(f"{number} follows {previous}")
        previous = number
        seen.setdefault(number, 0)
        seen[number] += 1

    lines = []
    for depth, number, title, slug in rows:
        indent = "" if depth == 2 else "  "
        lines.append(f"{indent}- [{number} {title}](#{slug})")
    duplicates = [n for n, c in seen.items() if c > 1]
    return "\n".join(lines), out_of_order + [f"{n} appears twice" for n in duplicates]


def decisions_toc(text: str) -> tuple[str, list[str]]:
    lines, previous = [], 0
    gaps = []
    for line in text.splitlines():
        m = DECISION.match(line)
        if not m:
            continue
        number, title = m.group(1), m.group(2).strip()
        lines.append(f"- [{number} {title}](#{anchor(f'{number}. {title}')})")
        n = int(number[1:])
        if previous and n != previous + 1:
            gaps.append(f"{number} follows D{previous}")
        previous = n
    return "\n".join(lines), gaps


def render(path: Path, body: str, notes: list[str], heading: str) -> str:
    text = path.read_text(encoding="utf-8")
    note = ""
    if notes:
        note = ("\n> **(!) Where this table departs from numeric order, the document does "
                "too, and the document wins.** " + "; ".join(notes)
                + ". Nothing is moved or renumbered to tidy this: the numbering is cited "
                "from hundreds of places and a table of contents is not a reason to "
                "break one.\n")
    block = f"{BEGIN}\n\n## {heading}\n{note}\n{body}\n\n{END}"
    if BEGIN in text:
        lo = text.index(BEGIN)
        hi = text.index(END) + len(END)
        return text[:lo] + block + text[hi:]
    # First insertion: after the document's opening prose, before its first section.
    first = re.search(r"^## ", text, re.M)
    at = first.start()
    return text[:at] + block + "\n\n" + text[at:]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="report, write nothing")
    a = ap.parse_args()

    targets = [
        (ROOT / "docs" / "MODELS.md", models_toc, "Contents"),
        (ROOT / "docs" / "DECISIONS.md", decisions_toc, "The decisions, in order"),
    ]
    changed = 0
    for path, builder, heading in targets:
        body, notes = builder(path.read_text(encoding="utf-8"))
        rendered = render(path, body, notes, heading)
        rows = body.count("\n") + 1
        print(f"  {path.relative_to(ROOT)}: {rows} entries"
              + (f"; {len(notes)} note(s): {'; '.join(notes)}" if notes else ""))
        if rendered != path.read_text(encoding="utf-8"):
            changed += 1
            if not a.check:
                path.write_text(rendered, encoding="utf-8")
    if a.check and changed:
        print(f"  {changed} document(s) would change")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
