#!/usr/bin/env python3
"""D84 / D83.1 route 1: deep_f32 at a MISSION's shape, generated by substitution.

`oxcaml/retrainer/deep_f32.ml` is a fixed, maxima-shaped network -- 16 inputs,
160 outputs, 75,360 parameters (`deep_f32.ml:35-41`). A mission flies its own
channel count, and a candidate at the maxima cannot replace its model
(`docs/MODELS.md` 72.4, D83 c.4). D83.1 costed three routes and recommended
this one: a second COMPILE-TIME instantiation, made by substitution the way the
ladder already makes its variants (`oxcaml_e3.sh:37`, `oxcaml_s60.sh:45-54`),
so the two cannot drift.

(!) ONLY THREE LINES MOVE, AND EACH ANCHOR MUST MATCH EXACTLY ONCE. `ins`,
`n_out` and `n_params` are substituted; every other byte is the template's.
The shapes are still constants after substitution, which is how D83.1 measured
the mission shape holding `[@zero_alloc strict]`: only their values differ.

(!) AT THE MAXIMA THE OUTPUT IS THE TEMPLATE, BYTE FOR BYTE. That is what makes
"the two cannot drift" checkable rather than argued:
`tests/test_retrainer_shape_is_generated.py` asserts it.

The box, and why it is this box:

    channels     1 .. 16    flight/include/sentinel/Config.hpp:23 MAX_CHANNELS
    predictions  1 .. 10    Config.hpp:32 MAX_PREDICTIONS
    hidden       [80, 80]   FIXED -- deep_f32.ml's hs and gw are the flown
                            architecture (src/sentinel_toolkit/fit.py:29)
    window       250        FIXED -- deep_f32.ml's t_max, the same source

A shape outside it is refused by name, not clamped. Moving hidden or window is
a different network, and would need its own ladder rather than a substitution.

It also writes `sentinel_cycle_shape.h`, which the F' component includes, so the
OCaml and the C++ read their extents from ONE generation step.

Standard library only: it runs before any virtualenv exists.

Usage:
    python3 scripts/oxcaml_shape.py --channels 8 --predictions 10 --out DIR
"""
from __future__ import annotations

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "oxcaml" / "retrainer" / "deep_f32.ml"

MAX_CHANNELS = 16       # Config.hpp:23
MAX_PREDICTIONS = 10    # Config.hpp:32
HIDDEN = 80             # deep_f32.ml hs, Config.hpp:29 MAX_HIDDEN
N_LAYERS = 2            # deep_f32.ml's two layers
N_GATES = 3             # GRU: reset, update, new
WINDOW = 250            # deep_f32.ml t_max

#: The template's three shape lines, verbatim. If deep_f32.ml moves any of them
#: the anchor stops matching and generation refuses, which is the point.
ANCHORS = {
    "ins": "let ins = 16                      (* Config.hpp MAX_INPUTS *)\n",
    "n_out": "let n_out = 160                   (* MAX_OUTPUTS *)\n",
    "n_params": "let n_params = 75360              "
                "(* ModelFile.hpp:34, at Config.hpp's maxima *)\n",
}


class ShapeError(ValueError):
    """A shape this generator refuses, with the reason."""


def parameter_count(channels: int, predictions: int) -> int:
    """The flat block's length, derived from the layer shapes.

    The same sum as `src/sentinel_export/format.py:parameter_count` and
    `deep_f32.ml`'s offsets (`o_hb + n_out`). Restated rather than imported so
    this runs with no virtualenv; the guard checks the two agree at every shape.
    """
    gw = N_GATES * HIDDEN
    total = 0
    previous = channels
    for _ in range(N_LAYERS):
        total += gw * previous + gw * HIDDEN + 2 * gw
        previous = HIDDEN
    outputs = predictions * channels
    return total + outputs * HIDDEN + outputs


def check_box(channels: int, predictions: int) -> None:
    if not 1 <= channels <= MAX_CHANNELS:
        raise ShapeError(f"channels {channels} is outside 1..{MAX_CHANNELS} "
                         f"(flight/include/sentinel/Config.hpp:23 MAX_CHANNELS)")
    if not 1 <= predictions <= MAX_PREDICTIONS:
        raise ShapeError(f"predictions {predictions} is outside 1..{MAX_PREDICTIONS} "
                         f"(flight/include/sentinel/Config.hpp:32 MAX_PREDICTIONS)")


def _line(name: str, value: int, maxima: int, width: int) -> str:
    """The template's own line at the maxima; a generated one elsewhere."""
    if value == maxima:
        return ANCHORS[name]
    text = f"let {name} = {value}"
    return f"{text.ljust(width)}(* D84: generated, mission shape *)\n"


def generate(channels: int, predictions: int, template: str) -> str:
    """deep_f32.ml at (channels, predictions). Raises ShapeError on refusal."""
    check_box(channels, predictions)
    for name, anchor in ANCHORS.items():
        found = template.count(anchor)
        if found != 1:
            raise ShapeError(f"anchor for {name} matched {found} times in "
                             f"deep_f32.ml; it must match exactly once")
    width = ANCHORS["ins"].index("(*")
    out = template
    out = out.replace(ANCHORS["ins"], _line("ins", channels, MAX_CHANNELS, width))
    out = out.replace(ANCHORS["n_out"], _line(
        "n_out", predictions * channels, MAX_PREDICTIONS * MAX_CHANNELS, width))
    out = out.replace(ANCHORS["n_params"], _line(
        "n_params", parameter_count(channels, predictions),
        parameter_count(MAX_CHANNELS, MAX_PREDICTIONS), width))
    return out


def header(channels: int, predictions: int) -> str:
    """The C side's extents, from the same generation step."""
    check_box(channels, predictions)
    n = parameter_count(channels, predictions)
    return (
        "/* D84: the retraining cycle's shape, GENERATED by scripts/oxcaml_shape.py.\n"
        " * Do not edit. The OCaml side's deep_f32.ml was generated in the same step\n"
        " * from the same two numbers, so the extents below and its constants agree. */\n"
        "#ifndef SENTINEL_CYCLE_SHAPE_H\n"
        "#define SENTINEL_CYCLE_SHAPE_H\n"
        "\n"
        f"#define SENTINEL_CYCLE_CHANNELS {channels}U\n"
        f"#define SENTINEL_CYCLE_PREDICTIONS {predictions}U\n"
        f"#define SENTINEL_CYCLE_WINDOW {WINDOW}U\n"
        f"#define SENTINEL_CYCLE_N_PARAMS {n}U\n"
        "\n"
        "#endif\n"
    )


def shape_dir_name(channels: int, predictions: int) -> str:
    return f"shape-c{channels}-p{predictions}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--channels", type=int, required=True)
    parser.add_argument("--predictions", type=int, required=True)
    parser.add_argument("--out", type=pathlib.Path, required=True)
    args = parser.parse_args(argv)
    try:
        ml = generate(args.channels, args.predictions,
                      TEMPLATE.read_text(encoding="utf-8"))
        h = header(args.channels, args.predictions)
    except ShapeError as exc:
        print(f"oxcaml_shape: refused -- {exc}", file=sys.stderr)
        return 2
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "deep_f32.ml").write_text(ml, encoding="utf-8")
    (args.out / "sentinel_cycle_shape.h").write_text(h, encoding="utf-8")
    print(f"   shape: {args.channels} channels, {args.predictions} predictions, "
          f"hidden [{HIDDEN}, {HIDDEN}], window {WINDOW}, "
          f"{parameter_count(args.channels, args.predictions):,} parameters")
    return 0


if __name__ == "__main__":
    sys.exit(main())
